-- Create star schema tables

-- time dimension
CREATE TABLE dim_time (
  time_id    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  dt         DATE UNIQUE NOT NULL,
  day_no     NUMBER,
  month_no   NUMBER,
  year_no    NUMBER,
  quarter_no NUMBER,
  is_weekend CHAR(1) DEFAULT 'N' CHECK (is_weekend IN ('Y','N'))
);

-- distribution center dimension
CREATE TABLE dim_dc (
  dc_id  VARCHAR2(50) PRIMARY KEY,
  name   VARCHAR2(400),
  region VARCHAR2(200),
  mgr    VARCHAR2(100)
);

-- author dimension
CREATE TABLE dim_author (
  author_id     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  first_name    VARCHAR2(100),
  last_name     VARCHAR2(100),
  country       VARCHAR2(100),
  primary_genre VARCHAR2(250)
);

-- product dimension
CREATE TABLE dim_product (
  product_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  author_id  NUMBER REFERENCES dim_author(author_id), -- stg_meta.author_id
  title      VARCHAR2(200),  -- stg_meta.publication_title
  category   VARCHAR2(200),  -- stg_meta.publication_cat
  language   VARCHAR2(200),  -- stg_meta.publication_lang
  edid       VARCHAR2(50) UNIQUE NOT NULL,
  typ        VARCHAR2(200)
);

-- vendor dimension
CREATE TABLE dim_vendor (
  vendor_id    VARCHAR2(50) PRIMARY KEY,
  vendor_name  VARCHAR2(200),
  vendor_score NUMBER
);

-- channel dimension
CREATE TABLE dim_channel (
  channel_id   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  channel_code VARCHAR2(50) UNIQUE NOT NULL,
  channel_name VARCHAR2(200)
);

-- fact table for production sales
CREATE TABLE fact_production_sales (
  fact_id          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  time_id          NUMBER REFERENCES dim_time(time_id) NOT NULL,
  dc_id            VARCHAR2(50) REFERENCES dim_dc(dc_id) NOT NULL,
  product_id       NUMBER REFERENCES dim_product(product_id) NOT NULL,
  channel_id       NUMBER REFERENCES dim_channel(channel_id) NOT NULL,
  vendor_id        VARCHAR2(50) REFERENCES dim_vendor(vendor_id),
  printrun         NUMBER,
  binding_cost     NUMBER,
  units_sold       NUMBER,
  unit_price       NUMBER,
  discount         NUMBER,
  revenue          NUMBER,
  returns_count    NUMBER,
  temperature      NUMBER,
  humidity         NUMBER,
  vendor_score     NUMBER,
  gross_margin_pct NUMBER,
  load_ts          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_fact_daily_grain UNIQUE (time_id, dc_id, product_id, channel_id, vendor_id)
);

COMMIT;

-- temporary run and then re-create fact_production_table
DROP TABLE fact_production_sales CASCADE CONSTRAINTS;
